language: node_js
node_js:
    - '0.10'
before_script:
    - npm install -g yo
    - npm install -g bower
    - npm install -g grunt-cli
    - npm install -g venus
    - bower install
script:
    - grunt jscs
    - venus run -t tests/ -c -n
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e9fa5782626e474068fa
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
