language: node_js
node_js:
    - '0.10'
before_script:
    - npm install -g yo
    - bower install
script: grunt test -v
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e9fa5782626e474068fa
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
