language: node_js
node_js:
    - '0.10'
before_script:
    - npm install -g yo
    - npm install -g venus@2.3.1
    - bower install
script:
    - grunt jscs
    - grunt exec:test:lib
    - grunt exec:test:storage
    - grunt exec:test:view
    - grunt exec:test:kernel
    - grunt exec:test:event
    - grunt exec:test:validator
    - grunt exec:test:topLevel
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e9fa5782626e474068fa
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
